/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border-shadcn))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
              "text-secondary": "#6B7280",
              "tertiary-fixed-dim": "#4edea3",
              "on-tertiary-fixed": "#002113",
              "on-secondary-fixed": "#2a1700",
              "surface": "#f9f9ff",
              "border-default": "rgba(0, 0, 0, 0.08)",
              "surface-container-highest": "#dce2f7",
              "on-surface-variant": "#464555",
              "on-tertiary-fixed-variant": "#005236",
              "info": "#3B82F6",
              "secondary-container": "#fea619",
              "background": "#f9f9ff",
              "secondary-fixed": "#ffddb8",
              "tertiary": "#005b3d",
              "on-error": "#ffffff",
              "inverse-surface": "#293040",
              "surface-tint": "#5244de",
              "border-subtle": "rgba(0, 0, 0, 0.04)",
              "bg-sidebar": "#FAFBFE",
              "primary-fixed-dim": "#c4c0ff",
              "surface-container-high": "#e1e8fd",
              "error": "#EF4444",
              "primary": "#4231cf",
              "primary-fixed": "#e3dfff",
              "brand-gradient": "linear-gradient(135deg, #5B4FE8 0%, #8B5CF6 50%, #A78BFA 100%)",
              "on-tertiary-container": "#77ffc2",
              "primary-container": "#5b4fe8",
              "tertiary-fixed": "#6ffbbe",
              "secondary": "#855300",
              "text-tertiary": "#9CA3AF",
              "on-secondary": "#ffffff",
              "inverse-primary": "#c4c0ff",
              "surface-bright": "#f9f9ff",
              "on-surface": "#141b2b",
              "on-primary-container": "#e8e4ff",
              "on-primary": "#ffffff",
              "error-container": "#ffdad6",
              "on-secondary-container": "#684000",
              "surface-container-low": "#f1f3ff",
              "on-primary-fixed": "#120068",
              "inverse-on-surface": "#edf0ff",
              "on-primary-fixed-variant": "#3824c7",
              "surface-container-lowest": "#ffffff",
              "bg-hover": "#F0F1F7",
              "focus-ring": "rgba(91, 79, 232, 0.4)",
              "outline": "#777586",
              "surface-container": "#e9edff",
              "on-secondary-fixed-variant": "#653e00",
              "bg-page": "#F7F8FC",
              "surface-dim": "#d3daef",
              "outline-variant": "#c8c4d8",
              "surface-variant": "#dce2f7",
              "on-tertiary": "#ffffff",
              "on-error-container": "#93000a",
              "bg-surface": "#FFFFFF",
              "on-background": "#141b2b",
              "secondary-fixed-dim": "#ffb95f",
              "tertiary-container": "#007650"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "page-padding": "28px",
              "card-padding": "24px",
              "base": "4px",
              "sm": "8px",
              "xs": "4px",
              "2xl": "24px",
              "content-max-width": "1360px",
              "lg": "16px",
              "3xl": "28px",
              "md": "12px",
              "sidebar-width": "256px",
              "topbar-height": "56px",
              "4xl": "32px",
              "xl": "20px"
      },
      "fontFamily": {
              "display-3xl": ["Outfit"],
              "body-base": ["Inter"],
              "headline-xl": ["Outfit"],
              "headline-2xl-mobile": ["Outfit"],
              "display-7xl": ["Outfit"],
              "headline-2xl": ["Outfit"],
              "body-sm": ["Inter"],
              "code-mono": ["JetBrains Mono"],
              "display-4xl": ["Outfit"],
              "label-xs": ["Inter"],
              "headline-lg": ["Inter"]
      },
      "fontSize": {
              "display-3xl": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.015em", "fontWeight": "700" }],
              "body-base": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "headline-xl": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
              "headline-2xl-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
              "display-7xl": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.025em", "fontWeight": "800" }],
              "headline-2xl": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.025em", "fontWeight": "700" }],
              "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "code-mono": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "display-4xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "label-xs": ["12px", { "lineHeight": "16px", "letterSpacing": "0.06em", "fontWeight": "600" }],
              "headline-lg": ["18px", { "lineHeight": "24px", "fontWeight": "600" }]
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
